title: 송채영
description: Ai, DeepLearning, MachineLearning Engineer
site_title: '@SongChaeYoung98 - 송채영'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: abhn
blog_url: https://www.nagekar.com
email: abhishek@nagekar.com
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/캡처.PNG

# Google Analytics ID
google_analytics: 