title: Song Chae Young
description: Ai, DeepLearning, MachineLearning Engineer
site_title: '송채영의 포트폴리오'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: SongChaeYoung98
blog_url: https://github.com/SongChaeYoung98/SongChaeYoung98.github.io
email: 0.0yeriel@gmail.com
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/profile-pic.jpg.jpg

# Google Analytics ID
google_analytics: 